name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Android SDK
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip -q cmdline-tools.zip -d $HOME/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV

      # Accept Android SDK Licenses
      - name: Accept Android SDK Licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
          sleep 5
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true

      # Install Android SDK Components
      - name: Install Android SDK Build-Tools and Platform
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "build-tools;36.0.0" "platforms;android-33" "ndk;25.2.9519653"
          # Verify installation
          ls -l $ANDROID_HOME/build-tools/36.0.0/ || echo "Build-Tools 36.0.0 not installed"
          $ANDROID_HOME/build-tools/36.0.0/aidl --version || echo "AIDL not found"

      # Install Buildozer and Dependencies
      - name: Install Buildozer and Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev zlib1g-dev
          pip install --user buildozer==1.5.0 cython==0.29.36

      # Build APK
      - name: Build APK
        run: |
          rm -rf /home/runner/.buildozer
          buildozer android clean || true
          buildozer -v android debug
        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk
          ANDROID_NDK_HOME: $HOME/android-sdk/ndk/25.2.9519653

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
