name: Build APK and Deploy HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # Buildozer works well with Python 3.8

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Android SDK Command Line Tools
      - name: Install Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip commandlinetools.zip -d /tmp/android-sdk
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv /tmp/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV

      # Accept Android SDK licenses
      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          sleep 5
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      # Install Android SDK Build-Tools and Platform
      - name: Install Android SDK Build-Tools and Platform
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;30.0.3" "platforms;android-30"
          ls -l $ANDROID_HOME/build-tools/

      # Debug SDK setup
      - name: Debug SDK and Build-Tools
        run: |
          echo "ANDROID_HOME: $ANDROID_HOME"
          ls -l $ANDROID_HOME
          ls -l $ANDROID_HOME/build-tools
          ls -l $ANDROID_HOME/build-tools/30.0.3
          $ANDROID_HOME/build-tools/30.0.3/aidl --version || echo "AIDL not found"

      # Install system dependencies for Buildozer
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 python3-dev ffmpeg \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            zlib1g-dev

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install --user buildozer kivy cython==0.29.36

      # Build APK with Buildozer
      - name: Build APK
        run: |
          buildozer android debug
        working-directory: .
        env:
          ANDROID_SDK_ROOT: $HOME/android-sdk

      # Upload APK as artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: localhostapp-apk
          path: bin/*.apk
          retention-days: 30

      # Deploy HTML to gh-pages branch
      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: false
          include_files: index.html
